### ISSUE TITLE
Onewire Interface and Mega IO

### ISSUE THREAD

**Issue by apostrophesoftware** [alexburcea2877/megaio-rpi#10]
Hello

I am using the Mega IO HAT to replace another HAT that I have been using, so far I am getting along very well.  The problem I have is that C code I have to read the temperature from a DS18B20 onewire temperature sensor is now failing to read the temperature from the sensor.

I have the sensor connected to the Raspberry Pi IO pins on the Mega IO HAT using the IO break out board.  I have enabled to onewire interface on the Pi and am using the wiring pi library pinMode, digitalRead and digitalWrite commands for accessing the one wire device

Should it be possible to use the onewire commands with the Mega IO HAT?

Thanks
Dave

**Comment by alexburcea2877** [comment]
Hi Dave,

Please tell me the Raspberry Pi pin used for DS18B20 communication?

Alex.

În mar., 2 apr. 2019 la 23:10, Apostrophe Software <notifications@github.com>
a scris:

**Comment by apostrophesoftware** [comment]
Hello Alex

I am using GPIO4 which is physical pin 7.

Thanks
Dave

**Comment by alexburcea2877** [comment]
Dave,

Unfortunately we use that pin for generate an event (check interrupt
example).
Use different pin for the sensor or cut the trace or wait me to release a
firmware update (set this pin as input when not used) and all the tool
needed  for firmware update.

Thanks for your patience,
Alex.

În mie., 3 apr. 2019 la 00:10, Apostrophe Software <notifications@github.com>
a scris:

**Comment by apostrophesoftware** [comment]
Hello Alex

I have resolved the problem with reading of the temperature on the one wire bus, as you suggested I changed the one wire bus pin and everything worked!

Now, I believe I have a problem with the breakout card that I have.  I am able to read the temperature when the device is connected directly to the pins on the Pi (without the MegaIO connected) and also connected to the pins on the Raspberry Pi IO header on the MegaIO card.  When I connect the break out card to the raspberry pi header on the mega IO board the one wire device is no longer visible.  running `ls /sys/bus/w1/devices` on the command line of the Pi produces no results!

I have connected the breakout card directly to a pi and also onto the io header on the mega io card with the same result!  Am I missing something?

Thanks
Dave

**Comment by alexburcea2877** [comment]
Please make sure you are interpreting correctly the break-out pins. They are reversed when you install it on RPI vs MegaIO. Count from pin1 to be sure you are using the proper pin. 

Also, rather than using software to debug your connection, try to use a meter to make sure your input is connected to the proper pin.

**Comment by apostrophesoftware** [comment]
Hello Alex

I looked at the diagrams on the web site and the pin out details on the back of the printed board and thought this may be case!  Now that the temperature sensor is connected to the correct pins I am able to read temperatures!

Is it possible to get versions of the breakout board that are correctly oriented for the raspberry Pi IO?

Thanks
Dave

**Comment by alexburcea2877** [comment]
The pins are always connected correctly, just the legend is misleading.
On the latest version we fixed it, you can purchase it on the website.

Alex.
