### ISSUE TITLE
404 in README

### ISSUE THREAD

**Issue by tehfink** [alexburcea2877/megaio-rpi#15]
The first link is broken: `https://www.sequentmicrosystems.com/megaio.html`

**Comment by alexburcea2877** [comment]
Solved, thank you for let us know.

În sâm., 28 mar. 2020 la 13:13, tehfink <notifications@github.com> a scris:

**Comment by PCRover** [comment]
Link is still broken.

**Comment by alexburcea2877** [comment]
Solve again
