### ISSUE TITLE
Relay as Pulse

### ISSUE THREAD

**Issue by olisoldier** [alexburcea2877/megaio-rpi#16]
Hello

Okay

I'm using the megaio-rpi, megaioind-rpi and relay8 cards, I'm loving doing several automations in my company.
I wonder if it is possible to turn the relay on / off command to pulse?

Thanks

**Comment by mbeffa** [comment]
It is obviously possible to turn the relays on and off. Each board has a self-test command which is "pulsing" the relays on and off at about 0.5 sec. interval. So I have to assume you mean something else. 

In case you want to know how fast you can "pulse" the relays, the answer is in their datasheet, for example 
https://www.mycomkits.com/reference/Songle_SRD(T73)_Relay.pdf

The relays have a turn on time of 10mS and a turn off of 5mS. So if you want to push them to the limit, you can "pulse" them at 15 mS and they will "sing" a tune of 66.66 Hz. 

This is something I would not recommend. The relays have a declared life expectancy of 10exp(7) minutes, so if you cycle them 66.66 x 60 = 4000 times/minute they will die after 
2500 minutes, or about a day and a half (41 hours). Without load. With a load they will die 100 times faster.

But maybe you mean something else by "pulsing"?

**Comment by olisoldier** [comment]
Yes

Thanks for the great explanation, it helped me understand the last lifetime.

What I would like to know if there are any commands ready via terminal or python that can pulse the relay, since my load waits for a pulse at its input to turn on the device.

The command example I expect and something like this relay8 0 1 pulse.

Thanks

**Comment by mbeffa** [comment]
Why couldn't you send three commands?
relay8 0 1
delay 1 sec
relay8 0 0

**Comment by olisoldier** [comment]
Solved my question
