### ISSUE TITLE
module object has no attribute 'add_opto_event'

### ISSUE THREAD

**Issue by o4fr** [alexburcea2877/megaio-rpi#2]
Hi,

Thank you for the awesome work.

When running the interrupt python example I get the following error:

```
root@raspberrypi3/usr/src/app/megaio-rpi/python# python it_example.py
Traceback (most recent call last):
  File "it_example.py", line 16, in <module>
    m.add_opto_event(0, 1, m.RISING, opto_callback)
AttributeError: 'module' object has no attribute 'add_opto_event'
```

**Comment by alexburcea2877** [comment]
Hi,

Make sure that "megaio.py" is in the same folder with "it_example.py" and
megaio.py is the last version.

import megaio  and call megaio.version() in python shell.


Alex.

În mie., 18 iul. 2018 la 11:01, o4fr <notifications@github.com> a scris:

**Comment by alexburcea2877** [comment]
Hi,

Sorry, my error, I forget to commit changes for megaio.py.
I will solve the problem shortly.

Thanks for feedback.

**Comment by alexburcea2877** [comment]
Hi,

Solve the problem, please check.
Thank you again for feedback,
Alex.

**Comment by o4fr** [comment]
Thank you for the quick support! I can now run the script.
