### ISSUE TITLE
Support for PWM output

### ISSUE THREAD

**Issue by o4fr** [alexburcea2877/megaio-rpi#3]
Hi, 

This is not an issue but a feature request.

Does the board support PWM output on any of the pins? If so, do you plan on implementing this functionality in this project?

Thanks for the great work!

**Comment by alexburcea2877** [comment]
Hi,

Megaio have some pins with pwm output functionality , and we plan in future to release a new firmware version to support that.

**Comment by o4fr** [comment]
Looking forward to it!
