### ISSUE TITLE
Python interrupt example - 5V-5VEXT

### ISSUE THREAD

**Issue by o4fr** [alexburcea2877/megaio-rpi#4]
I believe there is a typo in the python interrupt example. Shouldn't pin numbering for powering the optocuplers be 2 and 4?

https://github.com/alexburcea2877/megaio-rpi/blob/df2afcf29404d0d88076b53332db0b6ad9a55b62/python/it_example.py#L22

**Comment by alexburcea2877** [comment]
Hi, 

Yes, is a typo, the pins are 2 and 4.
Thanks again for accurate review.

**Comment by alexburcea2877** [comment]
Solved.
