### ISSUE TITLE
set_io_pin(stack, pin, val) fails to turn IO off

### ISSUE THREAD

**Issue by djiglesias** [alexburcea2877/megaio-rpi#6]
The set_io_pin(stack, pin, val) fails to turn the selected IO pin OFF. Reading through the Python functions provided in [__init__.py](https://github.com/SequentMicrosystems/megaio-rpi/blob/master/python/megaio/megaio/__init__.py) it is apparent that the wrong values are being sent to Mega-IO board on lines 205 and 207.

Currently, the `set_io_pin()` function checks the input value to be either a 1 or a 0 and then writes that value to the SMBus at the assigned register value, which is incorrect... the value written should only ever be the index of the selected PIN and the value provided by the user should only be user in the logic for which register to write to.

Currently:
```
def set_io_pin(stack, pin, val):
	bus = smbus.SMBus(1)
	
        ...

	if val == 1:	
		bus.write_byte_data(DEVICE_ADDRESS + stack, GPIO_SET_MEM_ADD, val)	
	else:
		bus.write_byte_data(DEVICE_ADDRESS + stack, GPIO_CLR_MEM_ADD, val)	
	return
```

Should be:
```
def set_io_pin(stack, pin, val):
	bus = smbus.SMBus(1)
	
        ...

	if val == 1:	
		bus.write_byte_data(DEVICE_ADDRESS + stack, GPIO_SET_MEM_ADD, pin)	
	else:
		bus.write_byte_data(DEVICE_ADDRESS + stack, GPIO_CLR_MEM_ADD, pin)	
	return
```

Writing a '0' to register address GPIO_CLR_MEM_ADD (0x1b) has no effect on the state of the IO, only writing the pin index (1-6) to the register has an effect as tested using an iPython terminal and an LED on IO pin 1.

```
from megaio import *
import smbus

bus = smbus.SMBus(1)
stack = 0
pin = 1
ON = 1
OFF = 0
IN = 1
OUT = 0

# Set IO to output.
set_io_pin_dir(stack, pin, OUT)

# Toggle LED with Python.
set_io_pin(stack, pin, ON)    # turns LED on
set_io_pin(stack, pin, OFF)   # no effect, should turn LED off

# Toggle LED with SMBus.
bus.write_bus_data(0x31, 0x1b, pin) # turns LED off
bus.write_bus_data(0x31, 0x1a, pin) # turns LED on
bus.write_bus_data(0x31, 0x1b, 0) # no effect, mimics current set_io_pin()
bus.write_bus_data(0x31, 0x1b, pin) # turns LED off

```

**Comment by djiglesias** [comment]
Same issue with `set_oc_pin()` on line 210.

**Comment by alexburcea2877** [comment]
Tank you for discover the bug, we will fix this.


În joi, 25 oct. 2018 la 00:04, Duncan Iglesias <notifications@github.com> a
scris:

**Comment by alexburcea2877** [comment]
Solve the problem, please check.

**Comment by djiglesias** [comment]
Pulled and reinstalled. Confirmed working! Thanks.
