### ISSUE TITLE
ADC value

### ISSUE THREAD

**Issue by ptorrent** [alexburcea2877/megaio-rpi#7]
Hello there !

Thanks for your work.

When I call this function:
```
get_adc_volt
```

The result value is always 1.44V (2048)

With this command: 
```
megaio 0 aread 7 
```
same result.

Can you explain to me why I still have a voltage when I have no cable connected to this input?

Am I doing something wrong?

Thanks a lot for your support

**Comment by alexburcea2877** [comment]
Hi,

Try to connect the channel to GND.
ADC channels have high impedance.

**Comment by ptorrent** [comment]
Do you mean ADC1 to GND ?

**Comment by alexburcea2877** [comment]
The channel you measure.

**Comment by alexburcea2877** [comment]
Timeout

**Comment by ptorrent** [comment]
THanks for your help ! Sorry for the late answer
