### ISSUE TITLE
How should I configure Raspberry Pi IO Card stack of 4 cards

### ISSUE THREAD

**Issue by shamruk** [alexburcea2877/megaio-rpi#8]
Hello, what should I do to get 4 "Raspberry Pi IO Card" working?
I see I need to configure hardware (jumpers), how can I do it? What should I connect with what?
Do I need to make some software for this?

**Comment by shamruk** [comment]
And how can I check if there is enough power to turn all 32 relays on at the same time?

**Comment by alexburcea2877** [comment]
Hi,

You should  use jumpers to set 4 different addresses (0, 1, 2 , 3), as in
data sheet.
You can access every card  in the stack by his address.
For safety reason, assume each relay consume maximum   100mA , add  maximum
current for raspberry and you find the power requirements .

Alex.

În lun., 11 mar. 2019 la 12:40, shamruk <notifications@github.com> a scris:

**Comment by shamruk** [comment]
Sorry, I'm new to electronics. Cannot get how should I connect jumpers. Tutorial tells to use 4-5 jumpers (4 contacts in total), cannot find any information what connect with what

**Comment by alexburcea2877** [comment]
Check the manual on https://www.sequentmicrosystems.com/megaio.html
Basically you have 2 connectors for jumpers and you can make 4 combinations
(0 =  no jumper install; 1 = install J1 ; 2  = install J2; 3 = install J1
and J2) .
In the manual you find all this well explained.



În lun., 11 mar. 2019 la 23:14, shamruk <notifications@github.com> a scris:

**Comment by alexburcea2877** [comment]
Timeout
