### ISSUE TITLE
Issue with C code linking on Pi (Raspbian Stretch)

### ISSUE THREAD

**Issue by apostrophesoftware** [alexburcea2877/megaio-rpi#9]
Hi

I am trying to incorporate the Mega IO HAT into a project that is currently developed in C and C++.  I am using the functions in comm.c and megio.h to simply turn the relays on and off.  The problem I have is quite strange, the linker is complaining that `gLed1HwAdd` and `gLed2HwAdd` have multiple definitions.  I have searched and can only find them defined in comm.c!

Do you have any suggestions as to where else they may defined?  I am linking to wiringPi, are they defined there? 

I am using Visual Studio 2017 to compile and link the files on the target Pi.  I have successfully compiled the source I downloaded from Git on the Pi using the make file so have all the libraries on the Pi.

Thanks
Dave

**Comment by alexburcea2877** [comment]
Hi Dave,

This two variable are for linking the megaIO relays with another board (Led Card) that is no longer available. You can remove all the functions that use this variables or declare them local variable inside the functions.
You can also declare them as constants (they never change). 

Alex.

**Comment by apostrophesoftware** [comment]
Hello Alex

Thanks for the quick response, I will remove the functions as suggested.

Thanks
Dave
